spring:
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
    locations: classpath:flyway
    baseline-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    Exposed: OFF
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN

media:
  cache: /src/cache
  outgoing: /src/output
  incoming: /src/input

streamit:
  address: http://streamit.service

executables:
  ffprobe: ffprobe
