spring:
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
    locations: classpath:flyway
    baseline-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    Exposed: OFF
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN
    no.iktdev.eventi: DEBUG

media:
  scratch: /src/scratch
  intermediate: /src/intermediate
  outbox: /src/outbox
  inbox: /src/inbox

streamit:
  base-url: ${PROCESSER_URL:http://processer:8080}

processer:
  base-url: http://processer:8080

executables:
  ffprobe: ffprobe
