spring.output.ansi.enabled=always
logging.level.org.apache.kafka=INFO
logging.level.root=INFO
logging.level.Exposed=OFF
logging.level.org.springframework.web.socket.config.WebSocketMessageBrokerStats = WARN
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
