CREATE TABLE TASKS
(
    ID            BIGINT        NOT NULL AUTO_INCREMENT,
    REFERENCE_ID  CHAR(36)     NOT NULL,
    TASK_ID       CHAR(36)     NOT NULL,
    TASK          VARCHAR(100) NOT NULL,
    STATUS        VARCHAR(50)  NOT NULL,
    DATA          LONGTEXT         NOT NULL,
    CLAIMED       BOOLEAN      NOT NULL DEFAULT FALSE,
    CLAIMED_BY    VARCHAR(100),
    CONSUMED      BOOLEAN      NOT NULL DEFAULT FALSE,
    LAST_CHECK_IN TIMESTAMP,
    PERSISTED_AT  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);
