CREATE TABLE FILE_PRESERVATION
(
    ID           BIGINT       NOT NULL AUTO_INCREMENT,
    FILE_NAME    VARCHAR(500) NOT NULL,
    FILE_PATH    TEXT         NOT NULL,
    PRESERVED    BOOLEAN      NOT NULL DEFAULT FALSE,
    PERSISTED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_FILE_PRESERVATION PRIMARY KEY (ID),
    CONSTRAINT UK_FILE_NAME UNIQUE (FILE_NAME)
);