ALTER TABLE EVENTS
    MODIFY PERSISTED_AT TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE TASKS
    MODIFY PERSISTED_AT TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY LAST_CHECK_IN TIMESTAMP(6) NULL;
