CREATE TABLE EVENTS
(
    ID           BIGINT       NOT NULL AUTO_INCREMENT,
    REFERENCE_ID CHAR(36)     NOT NULL,
    EVENT_ID     CHAR(36)     NOT NULL,
    EVENT        VARCHAR(100) NOT NULL,
    DATA         TEXT         NOT NULL,
    PERSISTED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),

    CONSTRAINT events_unique UNIQUE (REFERENCE_ID, EVENT_ID, EVENT)
);
