CREATE TABLE Events (
    id SERIAL PRIMARY KEY,
    REFERENCE_ID UUID NOT NULL,
    EVENT_ID UUID NOT NULL,
    EVENT VARCHAR(100) NOT NULL,
    DATA TEXT NOT NULL,
    PERSISTED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT events_unique UNIQUE (REFERENCE_ID, EVENT_ID, EVENT)
);
