CREATE TABLE Tasks (
    id SERIAL PRIMARY KEY,
    REFERENCE_ID UUID NOT NULL,
    TASK_ID UUID NOT NULL,
    TASK VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DATA TEXT NOT NULL,
    CLAIMED BOOLEAN NOT NULL DEFAULT FALSE,
    CLAIMED_BY VARCHAR(100),
    CONSUMED BOOLEAN NOT NULL DEFAULT FALSE,
    LAST_CHECK_IN TIMESTAMP,
    PERSISTED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
