spring:
  output:
    ansi:
      enabled: always
  web:
    resources:
      add-mappings: true
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  webflux:
    multipart:
      headers-charset: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    Exposed: OFF
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: INFO

media:
  scratch: /src/scratch
  intermediate: /src/intermediate
  outbox: /src/outbox
  inbox: /src/inbox

streamit:
  address: http://streamit.service

mediaprocessing:
  apps:
    coordinator:
      address: http://coordinator:8080
      health: /actuator/health
    processer:
      address: http://processer:8080
      health: /actuator/health
    converter:
      address: http://converter:8080
      health: /actuator/health
    metadata:
      address: http://metadata:8080
      health: /health
    watcher:
      address: http://watcher:8080
      health: /health