spring:
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
    locations: classpath:flyway
    baseline-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    Exposed: OFF
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN
    no.iktdev.eventi: DEBUG
    no.iktdev.mediaprocessing: DEBUG

media:
  scratch: /src/scratch
  intermediate: /src/intermediate
  outbox: /src/outbox
  inbox: /src/inbox

processer:
  coordinator-url: http://coordinator:8080
  coordinator-ping-on-startup: true
  allow-overwrite: false
  enableSegmentedTaskListener: true

executables:
  ffmpeg: ffmpeg
  ffprobe: ffprobe

directories:
  logs: /data/logs
