spring:
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
    locations: classpath:flyway
    baseline-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    Exposed: OFF
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN
    no.iktdev.eventi: DEBUG


media:
  cache: ${DIRECTORY_CONTENT_CACHE:/src/cache}
  outgoing: /src/output
  incoming: /src/input

processer:
  coordinator-url: ${COORDINATOR_URL:http://coordinator:8080}
  coordinator-ping-on-startup: true
  allow-overwrite: ${ALLOW_OVERWRITE:false}

executables:
  ffmpeg: ${SUPPORTING_EXECUTABLE_FFMPEG:ffmpeg}

directories:
  logs: ${LOG_DIR:/data/logs}
